
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace org.bn.mq.protocol {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "AliveRequest", IsSet = false  )]
    public class AliveRequest : IASN1PreparedElement {
                    
	private long timestamp_ ;
	[ASN1Integer( Name = "" )]
    
        [ASN1Element ( Name = "timestamp", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public long Timestamp
        {
            get { return timestamp_; }
            set { timestamp_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AliveRequest));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
