
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace org.bn.mq.protocol {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "DeliveredStatus")]
    public class DeliveredStatus : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "unknown", HasTag = true , Tag = 0 )]
            unknown , 
            [ASN1EnumItem ( Name = "delivered", HasTag = true , Tag = 1 )]
            delivered , 
            [ASN1EnumItem ( Name = "expired", HasTag = true , Tag = 2 )]
            expired , 
            [ASN1EnumItem ( Name = "partialDelivered", HasTag = true , Tag = 3 )]
            partialDelivered , 
            [ASN1EnumItem ( Name = "noneConsumers", HasTag = true , Tag = 4 )]
            noneConsumers , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DeliveredStatus));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
