
package org.bn.mq.protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DeliveryReport", isSet = false )
    public class DeliveryReport implements IASN1PreparedElement {
            
    @ASN1String( name = "", 
        stringType =  UniversalTag.PrintableString , isUCS = false )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 255L 
		
	   )
	   
        @ASN1Element ( name = "messageId", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private String messageId = null;
                
  
        @ASN1Element ( name = "status", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private DeliveredStatus status = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "consumerId", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private String consumerId = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "queuePath", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private String queuePath = null;
                
  
        
        public String getMessageId () {
            return this.messageId;
        }

        

        public void setMessageId (String value) {
            this.messageId = value;
        }
        
  
        
        public DeliveredStatus getStatus () {
            return this.status;
        }

        

        public void setStatus (DeliveredStatus value) {
            this.status = value;
        }
        
  
        
        public String getConsumerId () {
            return this.consumerId;
        }

        

        public void setConsumerId (String value) {
            this.consumerId = value;
        }
        
  
        
        public String getQueuePath () {
            return this.queuePath;
        }

        

        public void setQueuePath (String value) {
            this.queuePath = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DeliveryReport.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            