
package org.bn.mq.protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1Sequence ( name = "DeliveryReportMessage", isSet = false )
    public class DeliveryReportMessage {
            
    @ASN1String( name = "", 
        stringType =  UniversalTag.PrintableString , isUCS = false )
    @ASN1ValueRangeConstraint ( 
		min = 0L, 
		max = 10L ) 
	   
        @ASN1Element ( name = "messageId", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private String messageId = null;
                
  
        @ASN1Element ( name = "status", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private DeliveredStatus status = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		min = 0L, 
		max = 65535L ) 
	   
        @ASN1Element ( name = "deliveredCount", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Integer deliveredCount = null;
                
  
        
        public String getMessageId () {
            return this.messageId;
        }

        

        public void setMessageId (String value) {
            this.messageId = value;
        }
        
  
        
        public DeliveredStatus getStatus () {
            return this.status;
        }

        

        public void setStatus (DeliveredStatus value) {
            this.status = value;
        }
        
  
        
        public Integer getDeliveredCount () {
            return this.deliveredCount;
        }

        

        public void setDeliveredCount (Integer value) {
            this.deliveredCount = value;
        }
        
  
                    
        
        
        public void initWithDefaults() {
            
        }
            
    }
            