
package org.bn.mq.protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Choice ( name = "MessageBody" )
    public class MessageBody implements IASN1PreparedElement {
            
        @ASN1Element ( name = "messageUserBody", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private MessageUserBody messageUserBody = null;
                
  
        @ASN1Element ( name = "deliveryReport", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private DeliveryReport deliveryReport = null;
                
  
        @ASN1Element ( name = "subscribeRequest", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private SubscribeRequest subscribeRequest = null;
                
  
        @ASN1Element ( name = "subscribeResult", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private SubscribeResult subscribeResult = null;
                
  
        @ASN1Element ( name = "unsubscribeRequest", isOptional =  false , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private UnsubscribeRequest unsubscribeRequest = null;
                
  
        @ASN1Element ( name = "unsubscribeResult", isOptional =  false , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
    
	private UnsubscribeResult unsubscribeResult = null;
                
  
        @ASN1Element ( name = "lookupRequest", isOptional =  false , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private LookupRequest lookupRequest = null;
                
  
        @ASN1Element ( name = "lookupResult", isOptional =  false , hasTag =  true, tag = 7 , hasDefaultValue =  false  )
    
	private LookupResult lookupResult = null;
                
  
        @ASN1Element ( name = "aliveRequest", isOptional =  false , hasTag =  true, tag = 8 , hasDefaultValue =  false  )
    
	private AliveRequest aliveRequest = null;
                
  
        
        public MessageUserBody getMessageUserBody () {
            return this.messageUserBody;
        }

        public boolean isMessageUserBodySelected () {
            return this.messageUserBody != null;
        }

        private void setMessageUserBody (MessageUserBody value) {
            this.messageUserBody = value;
        }

        
        public void selectMessageUserBody (MessageUserBody value) {
            this.messageUserBody = value;
            
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setUnsubscribeResult(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                
                    setAliveRequest(null);
                            
        }

        
  
        
        public DeliveryReport getDeliveryReport () {
            return this.deliveryReport;
        }

        public boolean isDeliveryReportSelected () {
            return this.deliveryReport != null;
        }

        private void setDeliveryReport (DeliveryReport value) {
            this.deliveryReport = value;
        }

        
        public void selectDeliveryReport (DeliveryReport value) {
            this.deliveryReport = value;
            
                    setMessageUserBody(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setUnsubscribeResult(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                
                    setAliveRequest(null);
                            
        }

        
  
        
        public SubscribeRequest getSubscribeRequest () {
            return this.subscribeRequest;
        }

        public boolean isSubscribeRequestSelected () {
            return this.subscribeRequest != null;
        }

        private void setSubscribeRequest (SubscribeRequest value) {
            this.subscribeRequest = value;
        }

        
        public void selectSubscribeRequest (SubscribeRequest value) {
            this.subscribeRequest = value;
            
                    setMessageUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setUnsubscribeResult(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                
                    setAliveRequest(null);
                            
        }

        
  
        
        public SubscribeResult getSubscribeResult () {
            return this.subscribeResult;
        }

        public boolean isSubscribeResultSelected () {
            return this.subscribeResult != null;
        }

        private void setSubscribeResult (SubscribeResult value) {
            this.subscribeResult = value;
        }

        
        public void selectSubscribeResult (SubscribeResult value) {
            this.subscribeResult = value;
            
                    setMessageUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setUnsubscribeRequest(null);
                
                    setUnsubscribeResult(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                
                    setAliveRequest(null);
                            
        }

        
  
        
        public UnsubscribeRequest getUnsubscribeRequest () {
            return this.unsubscribeRequest;
        }

        public boolean isUnsubscribeRequestSelected () {
            return this.unsubscribeRequest != null;
        }

        private void setUnsubscribeRequest (UnsubscribeRequest value) {
            this.unsubscribeRequest = value;
        }

        
        public void selectUnsubscribeRequest (UnsubscribeRequest value) {
            this.unsubscribeRequest = value;
            
                    setMessageUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeResult(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                
                    setAliveRequest(null);
                            
        }

        
  
        
        public UnsubscribeResult getUnsubscribeResult () {
            return this.unsubscribeResult;
        }

        public boolean isUnsubscribeResultSelected () {
            return this.unsubscribeResult != null;
        }

        private void setUnsubscribeResult (UnsubscribeResult value) {
            this.unsubscribeResult = value;
        }

        
        public void selectUnsubscribeResult (UnsubscribeResult value) {
            this.unsubscribeResult = value;
            
                    setMessageUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                
                    setAliveRequest(null);
                            
        }

        
  
        
        public LookupRequest getLookupRequest () {
            return this.lookupRequest;
        }

        public boolean isLookupRequestSelected () {
            return this.lookupRequest != null;
        }

        private void setLookupRequest (LookupRequest value) {
            this.lookupRequest = value;
        }

        
        public void selectLookupRequest (LookupRequest value) {
            this.lookupRequest = value;
            
                    setMessageUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setUnsubscribeResult(null);
                
                    setLookupResult(null);
                
                    setAliveRequest(null);
                            
        }

        
  
        
        public LookupResult getLookupResult () {
            return this.lookupResult;
        }

        public boolean isLookupResultSelected () {
            return this.lookupResult != null;
        }

        private void setLookupResult (LookupResult value) {
            this.lookupResult = value;
        }

        
        public void selectLookupResult (LookupResult value) {
            this.lookupResult = value;
            
                    setMessageUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setUnsubscribeResult(null);
                
                    setLookupRequest(null);
                
                    setAliveRequest(null);
                            
        }

        
  
        
        public AliveRequest getAliveRequest () {
            return this.aliveRequest;
        }

        public boolean isAliveRequestSelected () {
            return this.aliveRequest != null;
        }

        private void setAliveRequest (AliveRequest value) {
            this.aliveRequest = value;
        }

        
        public void selectAliveRequest (AliveRequest value) {
            this.aliveRequest = value;
            
                    setMessageUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setUnsubscribeResult(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                            
        }

        
  

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(MessageBody.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            