
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "LstVersion") ]
    public class LstVersion: IASN1PreparedElement {
            
           
        private System.Collections.Generic.ICollection<Version>  val;

        
[ASN1SequenceOf( Name = "LstVersion", IsSetOf = true  )]

    
        [ASN1Element ( Name = "LstVersion", IsOptional =  false , HasTag =  true, Tag = 75, 
        TagClass =  TagClasses.Application  , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<Version> Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            

                    
        
        public LstVersion ()
        {
        }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(LstVersion));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

        
    }
            
}
