
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "OctetStringArray" ) ]
    public class OctetStringArray : IASN1PreparedElement {

	    private System.Collections.Generic.ICollection<byte[]> val = null; 
            
            [ASN1OctetString( Name = "" )]
    
            [ASN1SequenceOf( Name = "OctetStringArray", IsSetOf = false) ]

            public System.Collections.Generic.ICollection<byte[]> Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public void initValue() {
                this.Value = new System.Collections.Generic.List<byte[]>();
            }
            
            public void Add(byte[] item) {
                this.Value.Add(item);
            }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(OctetStringArray));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
