
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "SequenceWithNull", IsSet = false  )]
    public class SequenceWithNull : IASN1PreparedElement {
                    
	private string test_ ;
	[ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )]
        [ASN1Element ( Name = "test", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public string Test
        {
            get { return test_; }
            set { test_ = value;  }
        }
        
                
          
	private NullObject nullVal_ ;
	
        [ASN1Null ( Name = "nullVal" )]
    
        [ASN1Element ( Name = "nullVal", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public NullObject NullVal
        {
            get { return nullVal_; }
            set { nullVal_ = value;  }
        }
        
                
          
	private string test2_ ;
	[ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )]
        [ASN1Element ( Name = "test2", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public string Test2
        {
            get { return test2_; }
            set { test2_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SequenceWithNull));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
