
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "SequenceWithExplicitFields", IsSet = false  )]
    public class SequenceWithExplicitFields : IASN1PreparedElement {
                    
	private CertVersion version_ ;
	
        [ASN1Element ( Name = "version", IsOptional =  false , HasTag =  true, Tag = 0, IsImplicitTag = false  , HasDefaultValue =  true )  ]
    
        public CertVersion Version
        {
            get { return version_; }
            set { version_ = value;  }
        }
        
                
          
	private CertificateSerialNumber serialNumber_ ;
	
        [ASN1Element ( Name = "serialNumber", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public CertificateSerialNumber SerialNumber
        {
            get { return serialNumber_; }
            set { serialNumber_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	CertVersion param_Version =         
            new CertVersion ( 0);
        Version = param_Version;
    
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SequenceWithExplicitFields));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
