
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "Set1") ]
    public class Set1: IASN1PreparedElement {
            
           
        private Set1SequenceType  val;

        
       [ASN1PreparedElement]
       [ASN1Sequence ( Name = "Set1", IsSet = true  )]
       public class Set1SequenceType : IASN1PreparedElement {
                        
	private long set1ID_ ;
	[ASN1Integer( Name = "" )]
    
        [ASN1Element ( Name = "set1ID", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public long Set1ID
        {
            get { return set1ID_; }
            set { set1ID_ = value;  }
        }
        
                
  
                
                public void initWithDefaults() {
            		
                }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Set1SequenceType));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
       }
                
        [ASN1Element ( Name = "Set1", IsOptional =  false , HasTag =  true, Tag = 55, 
        TagClass =  TagClasses.Application  , HasDefaultValue =  false )  ]
    
        public Set1SequenceType Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            

                    
        
        public Set1 ()
        {
        }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Set1));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

        
    }
            
}
