
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "Set3") ]
    public class Set3: IASN1PreparedElement {
            
           
        private Set3SequenceType  val;

        
       [ASN1PreparedElement]
       [ASN1Sequence ( Name = "Set3", IsSet = true  )]
       public class Set3SequenceType : IASN1PreparedElement {
                        
	private Set2 set2_ ;
	
        [ASN1Element ( Name = "set2", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public Set2 Set2
        {
            get { return set2_; }
            set { set2_ = value;  }
        }
        
                
  
                
                public void initWithDefaults() {
            		
                }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Set3SequenceType));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
       }
                
        [ASN1Element ( Name = "Set3", IsOptional =  false , HasTag =  true, Tag = 124, 
        TagClass =  TagClasses.Application  , HasDefaultValue =  false )  ]
    
        public Set3SequenceType Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            

                    
        
        public Set3 ()
        {
        }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Set3));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

        
    }
            
}
