
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "Set4") ]
    public class Set4: IASN1PreparedElement {
            
           
        private System.Collections.Generic.ICollection<Set3>  val;

        
[ASN1SequenceOf( Name = "Set4", IsSetOf = true  )]

    
        [ASN1Element ( Name = "Set4", IsOptional =  false , HasTag =  true, Tag = 61, 
        TagClass =  TagClasses.Application  , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<Set3> Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            

                    
        
        public Set4 ()
        {
        }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Set4));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

        
    }
            
}
