
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "TaggedSequence") ]
    public class TaggedSequence: IASN1PreparedElement {
            
           
        private TaggedSequenceSequenceType  val;

        
       [ASN1PreparedElement]
       [ASN1Sequence ( Name = "TaggedSequence", IsSet = false  )]
       public class TaggedSequenceSequenceType : IASN1PreparedElement {
                        
	private string type1_ ;
	
        private bool  type1_present = false ;
	[ASN1String( Name = "", 
        StringType =  UniversalTags.VisibleString , IsUCS = false )]
        [ASN1Element ( Name = "type1", IsOptional =  true , HasTag =  true, Tag = 7 , HasDefaultValue =  false )  ]
    
        public string Type1
        {
            get { return type1_; }
            set { type1_ = value; type1_present = true;  }
        }
        
                
  
        public bool isType1Present () {
            return this.type1_present == true;
        }
        
                
                public void initWithDefaults() {
                    
                }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TaggedSequenceSequenceType));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
       }
                
        [ASN1Element ( Name = "TaggedSequence", IsOptional =  false , HasTag =  true, Tag = 8, 
        TagClass =  TagClasses.Application  , HasDefaultValue =  false )  ]
    
        public TaggedSequenceSequenceType Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            

                    
        
        public TaggedSequence ()
        {
        }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TaggedSequence));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

        
    }
            
}
