
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "TestPRN") ]
    public class TestPRN: IASN1PreparedElement {

            private String val;
    
            [ASN1String( Name = "TestPRN", 
        StringType =  UniversalTags.PrintableString , IsUCS = false) ]
            
            public String Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public TestPRN() {
            }

            public TestPRN(String val) {
                this.val = val;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TestPRN));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
