
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "TestLongTag2") ]
    public class TestLongTag2 : IASN1PreparedElement {
                    
        
	private TestLongTag2Choice testa_ ;
        private bool  testa_selected = false ;
        
        
        
        [ASN1Element ( Name = "testa", IsOptional =  false , HasTag =  true, Tag = 33 , HasDefaultValue =  false )  ]
    
        public TestLongTag2Choice Testa
        {
            get { return testa_; }
            set { selectTesta(value); }
        }
        
                
          
        public bool isTestaSelected () {
            return this.testa_selected ;
        }

        


        public void selectTesta (TestLongTag2Choice val) {
            this.testa_ = val;
            this.testa_selected = true;
            
                        
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TestLongTag2));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
