
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "TestParent", IsSet = false  )]
    public class TestParent : IASN1PreparedElement {
                    
	private long field1_ ;
	[ASN1Integer( Name = "" )]
    
        [ASN1Element ( Name = "field1", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public long Field1
        {
            get { return field1_; }
            set { field1_ = value;  }
        }
        
                
          
	private byte[] field2_ ;
	
        private bool  field2_present = false ;
	[ASN1OctetString( Name = "" )]
    
        [ASN1Element ( Name = "field2", IsOptional =  true , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public byte[] Field2
        {
            get { return field2_; }
            set { field2_ = value; field2_present = true;  }
        }
        
                
          
	private string field3_ ;
	[ASN1String( Name = "", 
        StringType =  UniversalTags.UTF8String , IsUCS = false )]
        [ASN1Element ( Name = "field3", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  true )  ]
    
        public string Field3
        {
            get { return field3_; }
            set { field3_ = value;  }
        }
        
                
          
	private long field4_ ;
	[ASN1Integer( Name = "" )]
    
        [ASN1Element ( Name = "field4", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public long Field4
        {
            get { return field4_; }
            set { field4_ = value;  }
        }
        
                
  
        public bool isField2Present () {
            return this.field2_present == true;
        }
        

            public void initWithDefaults() {
            	string param_Field3 =         
            "Sssdsd";
        Field3 = param_Field3;
    
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TestParent));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
