
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace test.org.bn.coders.test_asn {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "TestIR" )]
    public class TestIR: IASN1PreparedElement {
    
            private int val;
            
            [ASN1Integer( Name = "TestIR" )]
            [ASN1ValueRangeConstraint ( 
		
		Min = 1L, 
		
		Max = 5L 
		
		) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public TestIR() {
            }

            public TestIR(int value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(TestIR));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
