
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "Set3" )
    public class Set3 implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "Set3" , isSet = true )
       public static class Set3SequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "set2", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Set2 set2 = null;
                
  
        
        public Set2 getSet2 () {
            return this.set2;
        }

        

        public void setSet2 (Set2 value) {
            this.set2 = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_Set3SequenceType;
        }

       private static IASN1PreparedElementData preparedData_Set3SequenceType = CoderFactory.getInstance().newPreparedElementData(Set3SequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "Set3", isOptional =  false , hasTag =  true, tag = 124, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private Set3SequenceType  value;        

        
        
        public Set3 () {
        }
        
        
        
        public void setValue(Set3SequenceType value) {
            this.value = value;
        }
        
        
        
        public Set3SequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Set3.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            