
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "Set7" )
    public class Set7 implements IASN1PreparedElement {
                
        

       @ASN1PreparedElement
       @ASN1Sequence ( name = "Set7" , isSet = true )
       public static class Set7SequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "set6", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Set6 set6 = null;
                
  
        
        public Set6 getSet6 () {
            return this.set6;
        }

        

        public void setSet6 (Set6 value) {
            this.set6 = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_Set7SequenceType;
        }

       private static IASN1PreparedElementData preparedData_Set7SequenceType = CoderFactory.getInstance().newPreparedElementData(Set7SequenceType.class);
                
       }

       
                
        @ASN1Element ( name = "Set7", isOptional =  false , hasTag =  true, tag = 90, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private Set7SequenceType  value;        

        
        
        public Set7 () {
        }
        
        
        
        public void setValue(Set7SequenceType value) {
            this.value = value;
        }
        
        
        
        public Set7SequenceType getValue() {
            return this.value;
        }            
        

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Set7.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            