
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "TestLongTag2Choice", isSet = false )
    public class TestLongTag2Choice implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "testb", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Long testb = null;
                
  
        
        public Long getTestb () {
            return this.testb;
        }

        

        public void setTestb (Long value) {
            this.testb = value;
        }
        
  
                    
        
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TestLongTag2Choice.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            