
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "TestReal" )
    public class TestReal implements IASN1PreparedElement {
    
            @ASN1Real ( name = "TestReal" )
            
            private Double value;
            
            public TestReal() {
            }

            public TestReal(Double value) {
                this.value = value;
            }
            
            public void setValue(Double value) {
                this.value = value;
            }
            
            public Double getValue() {
                return this.value;
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TestReal.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            