
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "TestParent", isSet = false )
    public class TestParent implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "field1", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Long field1 = null;
                
  @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "field2", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private byte[] field2 = null;
                
  
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
        @ASN1Element ( name = "field3", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  true  )
    
	private String field3 = null;
                
  @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "field4", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private Long field4 = null;
                
  
        
        public Long getField1 () {
            return this.field1;
        }

        

        public void setField1 (Long value) {
            this.field1 = value;
        }
        
  
        
        public byte[] getField2 () {
            return this.field2;
        }

        
        public boolean isField2Present () {
            return this.field2 != null;
        }
        

        public void setField2 (byte[] value) {
            this.field2 = value;
        }
        
  
        
        public String getField3 () {
            return this.field3;
        }

        

        public void setField3 (String value) {
            this.field3 = value;
        }
        
  
        
        public Long getField4 () {
            return this.field4;
        }

        

        public void setField4 (Long value) {
            this.field4 = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            String param_Field3 =         
            new String ("Sssdsd");
        setField3(param_Field3);
    
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TestParent.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            