
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "UTF8StringArray" )
    public class UTF8StringArray implements IASN1PreparedElement {
                
            
    @ASN1String( name = "", 
        stringType = UniversalTag.UTF8String , isUCS = false )
    
            @ASN1SequenceOf( name = "UTF8StringArray" , isSetOf = false)
	    private java.util.Collection<String> value = null; 
    
            public UTF8StringArray () {
            }
        
            public UTF8StringArray ( java.util.Collection<String> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<String> value) {
                this.value = value;
            }
            
            public java.util.Collection<String> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<String>()); 
            }
            
            public void add(String item) {
                value.add(item);
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(UTF8StringArray.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            